### PR TITLE
Fixed issues regarding responsive(mobile) view

### PR DESCRIPTION
**Pull request by Neilblaze**
This site, `http://bioconda.github.io` is not properly optimized for mobile view. Still when this site is being open in mobile, the site looks like this - 
unoptimized

So, thus I tweaked the site a little bit into the `style.css` & `alabaster.css` inside `./static` to fix the overlap & the `sphinxsidebar` for better mobile optimized view. Now, it looks like - 
Optimized

For desktop view, it was previously like - 
unoptimized PC

Now it's like - 
Optimized PC

Also, last but not the least, the footer credits has been aligned to `center` from `right`
i.e. from this 
Footer right-aligned

to this
Footer centered

### CODE REVIEW

**Comment by Neilblaze** [comment]
@cbrueffer can you please review this?

**Comment by Neilblaze** [comment]
@epruesse can you please review this?

**Comment by Neilblaze** [comment]
@johanneskoester a bit off topic request :sweat_smile: 
Can I get an invite to the Bioconda Org please? :smiley:

**Comment by epruesse** [comment]
Apologies for not seeing this months ago. Your invitation is out, Neil!

**Comment by epruesse** [comment]
Thanks for fixing the mobile view. The site could do with some updates and visual fixes. It's been a while since I was messing with it, and it's not my "forte"

**Pull request merged**
