### PR TITLE
Fix inconsistency in troubleshooting.rst

### PR DESCRIPTION
**Pull request by epruesse**

### CODE REVIEW

**Comment by epruesse** [comment]
ping @bioconda/core - can someone merge this?

**Comment by bgruening** [comment]
@epruesse the curly braces are actually good to use, isn't it? Should we keep them?

**Comment by epruesse** [comment]
(Summary: missing braces where they are needed fails usually during dev and testing, missing quotation marks fails on the user side)

**Comment by bgruening** [comment]
I agree with the quotes obviously, but I think the braces are good to have at least in our documentation :)

**Comment by epruesse** [comment]
There you go :)

**Comment by bgruening** [comment]
Merci!

**Pull request merged**
